name: Discord noti

on: [push]

jobs:
    discord-send-message:
        runs-on: ubuntu-latest
        name: Discord Commits
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1

            - name: Send message to Discord
              uses: Sniddl/discord-commits@v1.3
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  message:
                      "Successful commit to **{{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}**.\nDiff: {{ github.context.payload.compare }}"
                  embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'
